"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "*")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "") != "False"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")

if DEBUG:
    ALLOWED_HOSTS = ["*"]

    INTERNAL_IPS = ["127.0.0.1"]
    DEBUG_TOOLBAR_CONFIG = {"INTERCEPT_REDIRECTS": False}


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Database:
    "django.contrib.postgres",
    # Third apps:
    "django_extensions",
    "django_filters",
    "rest_framework",
    # "rest_framework.authtoken",
    # "dj_rest_auth",
    # My apps:
    "storehouse",
]

if DEBUG:
    INSTALLED_APPS.append("debug_toolbar")
    # INSTALLED_APPS.append("django_celery_results")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if DEBUG:
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            (os.path.join(BASE_DIR, "templates")),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("NAME_DB"),
        "USER": os.environ.get("USER_DB"),
        "PASSWORD": os.environ.get("PASSWORD_DB"),
        "HOST": os.environ.get("HOST_DB"),
        "PORT": os.environ.get("PORT_DB"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Kiev"

USE_I18N = True

USE_TZ = True

# Celery Configuration Options
# CELERY_TASK_TRACK_STARTED = True
# CELERY_TASK_TIME_LIMIT = 30 * 60

# CELERY_RESULT_BACKEND = 'amqp://localhost:5672'
# CELERY_RESULT_BACKEND = 'django-db'
# CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
# CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")

# CELERY_BROKER_URL = 'amqp://localhost:5672'
# CELERY_BROKER_URL = 'redis://localhost:6379/0'
# CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "amqp://localhost:5672")

# CELERY_CACHE_BACKEND = "django-cache"
# CELERY_CACHE_BACKEND = "default"
#
# CELERY_ACCEPT_CONTENT = ["application/json"]
# CELERY_TASK_SERIALIZER = "json"
# CELERY_RESULT_SERIALIZER = "json"
# CELERY_TIMEZONE = "Europe/Kiev"


# Cache time to live is 15 seconds:
# CACHE_TTL = 15
# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://localhost:6379",
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#             "db": "10",
#             "parser_class": "redis.connection.PythonParser",
#             "pool_class": "redis.BlockingConnectionPool",
#         },
#     }
# }


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "storehouse/static/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "storehouse/static")]


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CART_SESSION_ID = "cart"

# REST_FRAMEWORK = {
#     "EXCEPTION_HANDLER": "rest_framework_json_api.exceptions.exception_handler",
#     "DEFAULT_PARSER_CLASSES": ("rest_framework_json_api.parsers.JSONParser",),
#     "DEFAULT_RENDERER_CLASSES": (
#         "rest_framework_json_api.renderers.JSONRenderer",
#         "rest_framework.renderers.BrowsableAPIRenderer",
#     ),
#     "DEFAULT_METADATA_CLASS": "rest_framework_json_api.metadata.JSONAPIMetadata",
#     "DEFAULT_FILTER_BACKENDS": (
#         "rest_framework_json_api.filters.QueryParameterValidationFilter",
#         "rest_framework_json_api.filters.OrderingFilter",
#         "rest_framework_json_api.django_filters.DjangoFilterBackend",
#         "rest_framework.filters.SearchFilter",
#     ),
#     "SEARCH_PARAM": "filter[search]",
#     "TEST_REQUEST_RENDERER_CLASSES": ("rest_framework_json_api.renderers.JSONRenderer",),
#     "TEST_REQUEST_DEFAULT_FORMAT": "vnd.api+json",
# }

# Add to test email:
if not DEBUG:
    DEFAULT_FROM_EMAIL = "BookShop <noreply@bookshop.com>"
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.environ.get("EMAIL_HOST")
    EMAIL_USE_TLS = True
    EMAIL_PORT = os.environ.get("EMAIL_PORT")
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    EMAIL_HOST_USER = "admin@admin.com"

    # Email configuration
    # EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    # EMAIL_HOST = "mailhog"
    # EMAIL_PORT = "25"
    # EMAIL_HOST_USER = ""
    # EMAIL_HOST_PASSWORD = ""
    # EMAIL_USE_SSL = False

##################
# USER_AGENTS_CACHE = "default"
#
# REDIS_URL = env("REDIS_URL", default="redis://redis:6379/0")
# REDIS_CACHE = env("REDIS_CACHE", default="redis:6379")
# AMQP_URL = env("AMQP_URL", default="amqp://rabbitmq:5672")
#
# BROKER_URL = AMQP_URL
# CELERY_result_backend = REDIS_URL
# CELERY_BROKER_URL = BROKER_URL
#
# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": [
#             REDIS_URL,
#         ],
#         "OPTIONS": {
#             "CONNECTION_POOL_CLASS": "redis.BlockingConnectionPool",
#             "CONNECTION_POOL_CLASS_KWARGS": {
#                 "max_connections": 50,
#                 "timeout": 20,
#             },
#             "MAX_CONNECTIONS": 1000,
#             "PICKLE_VERSION": -1,
#         },
#     },
# }
####################


REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 5,
    # "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",
    # "DEFAULT_PERMISSION_CLASSES": (
    #     # "rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly",
    #     # "rest_framework.permissions.IsAuthenticated",
    #     "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    # ),
    # "DEFAULT_AUTHENTICATION_CLASSES": (
    #     # "rest_framework.authentication.BasicAuthentication",
    #     "rest_framework.authentication.SessionAuthentication",
    #     "rest_framework.authentication.TokenAuthentication",
    # ),
}
